### ISSUE TITLE
Outreach to potential attendees / participants 

### ISSUE THREAD

**Issue by mheadd** [UpstateData/data-summit#6]
We want to reach out to groups that have members who may be interested in attending the event. We should conduct out reach to groups like:

- [ ] [NYS Association of Counties](http://www.nysac.org/index.asp)
- [ ] [NYS Association of County Clerks](http://www.nysac.org/countyclerks)
- [ ] [NYS Association of Towns](http://www.nytowns.org/)
- [x] [Center for Technology in Government](https://www.ctg.albany.edu/)
- [ ] [New York State Conference of Mayors](https://www.nycom.org/)
- [ ] [New York State City/County Management Association](http://www.nyscma.govoffice.com/)
- [ ] [Bloomberg Philanthropies / What Works Cities](https://whatworkscities.bloomberg.org/)

**Comment by mheadd** [comment]
[New York State City/County Management Association](New York State City/County Management Association)

**Comment by mheadd** [comment]
The [Rockefeller Institute](http://rockinst.org/data-hub/) has a data hub, and might be interested in participating.

**Comment by samedelstein** [comment]
Thoughts on informing:
- Data Science for Social Good
- Civic Analytics Network (Harvard)
- MicrosoftNY - they tweet about upstate data stuff a lot

**Comment by mheadd** [comment]
Great idea
