### ISSUE TITLE
Event website

### ISSUE THREAD

**Issue by mheadd** [UpstateData/data-summit#8]
We need a simple web site for the event. Somewhere to post info, and mailing list + registration links

**Comment by zeddkay** [comment]
Hi @mheadd , I'm looking for beginner bugs to work on. I know HTML, CSS, Javascript, and PHP. Is there anyway I can help to create this website? Please let me know. Thanks.

**Comment by mheadd** [comment]
Hi, @zeddkay! Thanks for reaching out!

Right now, I'm just using a simple [Bootstrap template](https://getbootstrap.com/) that you can see [here](https://upstatedata.github.io/data-summit/). 

Most of the work will probably be adding in content that I haven't written yet. But I'd be open to any ideas that you might have for what you think would look good in a conference web site. Can you have any elements that you think might be god to include?

Happy to review a [pull request](https://help.github.com/articles/creating-a-pull-request/) of you want to send one for layout, styling, etc. 

Thanks!

**Comment by zeddkay** [comment]
Hi @mheadd. I've submitted a PR at #9, please take a look and let me know if I can help with anything. I also think if you have photos and details of the conference speakers, it would be a nice page to include. Thank you.
